# Firefox on Wayland
dot_desktop_path = "/usr/share/applications/firefox.desktop"
gtk_application = true

[import_conf]
copy = [".mozzila"]

[config]
executable_name = "/usr/bin/firefox"
services = ["wayland", "network", "pulse_audio", "notify"]

[config.service.home_share]
home_paths = [ "Downloads",]